workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1  # Use this for building APK on macOS
    environment:
      flutter: stable
      groups:
        - keystore_credential
    scripts:
      - name: Clean Flutter Cache
        script: |
         flutter clean
         flutter pub get
      - name: Set up Keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
      - name: Ensure Flutter V2 Embedding
        script: |
          # Find and replace all occurrences of V1 embedding with V2 embedding
          find . -type f -exec sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' {} +      - name: Clean and Upgrade
        script: |
         flutter clean
         flutter pub upgrade --major-versions
         flutter pub get
      - name: Build APK (Flutter V2)
        script: |
         flutter build apk --release --no-shrink --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
