workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: "3.19.5"
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-shrink --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
