workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.plumbing_quote"
    scripts:
      - name: Ensure Flutter V2 Embedding
        script: |
          # Find and replace all occurrences of V1 embedding with V2 embedding
          find . -type f -exec sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' {} +

      - name: Clean and Upgrade Dependencies
        script: |
          flutter clean
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release --no-shrink --split-per-abi

      - name: Ensure Flutter V2 Embedding
        script: |
          # Only modify Android-related files (avoid pubspec.yaml)
          find android app lib -type f -name "*.kt" -o -name "*.xml" -o -name "*.gradle" | while read file; do
            sed -i'' -e 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' "$file"
          done

    artifacts:
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk

    publishing:
      email:
        recipients:
          - jaydenrules.jr@gmail.com
