workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: "3.19.5"
    scripts:
      - name: Clean up old embedding and artifacts
        script: |
          echo "Deleting old artifacts..."
          rm -rf .android .dart_tool build
          echo "Checking for V1 embedding..."
          grep -r 'io.flutter.app.FlutterActivity' . || echo "No V1 embedding found."
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-shrink --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
